name: Build and Deploy App

on:
  push:
    branches: ['master']

jobs:
  build-deploy:
    name: Build and Deploy App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Unit Tests
        run: ./gradlew test
      - name: Build the application
        run: ./gradlew clean build